# This rule is not used by the project trashed-resources itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to mox.app.br resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: trashed-resources
    app.kubernetes.io/managed-by: kustomize
  name: trashedresources-viewer-role
rules:
- apiGroups:
  - mox.app.br
  resources:
  - trashedresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mox.app.br
  resources:
  - trashedresources/status
  verbs:
  - get
